/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Componentes;

/**
 *
 * @author EMILIANISOMASCOS
 */
public class BarraTituloForm extends javax.swing.JPanel {

    /**
     * Creates new form BarraTituloForm
     */
    public BarraTituloForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEscalable1 = new Labels.LabelEscalable();

        setBackground(new java.awt.Color(1, 15, 30));
        setPreferredSize(new java.awt.Dimension(1530, 45));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEscalable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoW.png"))); // NOI18N
        labelEscalable1.setPreferredSize(new java.awt.Dimension(38, 30));
        add(labelEscalable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 8, -1, -1));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Labels.LabelEscalable labelEscalable1;
    // End of variables declaration//GEN-END:variables
}
