/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;
import java.awt.Font;
import java.io.InputStream;


/**
 *
 * @author Computacion
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        jLabel1.setFont(cargarFuente("DMSans-Bold.ttf", 28f));
        

    
    

    }   
    
    private Font cargarFuente(String archivo, float tamaño) {
    try {
        InputStream fuente = getClass().getResourceAsStream(
                "/Font/DMSans/" + archivo
        );

        if (fuente == null) {
            System.out.println("No se encontró la fuente: " + archivo);
            return new Font("Arial", Font.PLAIN, (int) tamaño);
        }

        return Font.createFont(Font.TRUETYPE_FONT, fuente)
                   .deriveFont(tamaño);

    } catch (Exception e) {
        e.printStackTrace();
        return new Font("Arial", Font.PLAIN, (int) tamaño);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelEscalable2 = new Labels.LabelEscalable();
        labelEscalable4 = new Labels.LabelEscalable();
        labelEscalable5 = new Labels.LabelEscalable();
        labelEscalable3 = new Labels.LabelEscalable();
        labelEscalable1 = new Labels.LabelEscalable();
        labelEscalable6 = new Labels.LabelEscalable();
        labelEscalable7 = new Labels.LabelEscalable();
        jLabel1 = new javax.swing.JLabel();
<<<<<<< HEAD
        botonDerretido1 = new Componentes.BotonDerretido();
        texBox1 = new Labels.TexBox();
        texBoxPassword1 = new Labels.TexBoxPassword();
=======
        jPasswordField1 = new javax.swing.JPasswordField();
        botonDerretido1 = new Componentes.BotonDerretido();
        texBox1 = new Labels.TexBox();
>>>>>>> 361dfb21028027730bd35f4a3cde26889096c033

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEscalable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        labelEscalable2.setText("labelEscalable2");
        jPanel2.add(labelEscalable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 300, 180));

        labelEscalable4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BbebidaLogo.png"))); // NOI18N
        labelEscalable4.setText("labelEscalable4");
        jPanel2.add(labelEscalable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 200, 300));

        labelEscalable5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PapasLogo.png"))); // NOI18N
        labelEscalable5.setText("labelEscalable5");
        jPanel2.add(labelEscalable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 160, 220));

        labelEscalable3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MeseLogo.png"))); // NOI18N
        labelEscalable3.setText("labelEscalable3");
        jPanel2.add(labelEscalable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 400, 120));

        labelEscalable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoLogo.png"))); // NOI18N
        labelEscalable1.setText("labelEscalable1");
        jPanel2.add(labelEscalable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 370, 330));

        labelEscalable6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PuntosLogo.png"))); // NOI18N
        labelEscalable6.setText("labelEscalable6");
        jPanel2.add(labelEscalable6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 70, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 810));

        labelEscalable7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MiniLogo.png"))); // NOI18N
        labelEscalable7.setText("labelEscalable7");
        jPanel1.add(labelEscalable7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 100, 110));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Bienvenido a Waldonald's!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 550, 70));
<<<<<<< HEAD
        jPanel1.add(botonDerretido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 510, -1, -1));
        jPanel1.add(texBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 360, 50));
        jPanel1.add(texBoxPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 360, 50));
=======

        jPasswordField1.setText("jPasswordField1");
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 380, 50));
        jPanel1.add(botonDerretido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 510, -1, -1));
        jPanel1.add(texBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 360, 50));
>>>>>>> 361dfb21028027730bd35f4a3cde26889096c033

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.BotonDerretido botonDerretido1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
<<<<<<< HEAD
=======
    private javax.swing.JPasswordField jPasswordField1;
>>>>>>> 361dfb21028027730bd35f4a3cde26889096c033
    private Labels.LabelEscalable labelEscalable1;
    private Labels.LabelEscalable labelEscalable2;
    private Labels.LabelEscalable labelEscalable3;
    private Labels.LabelEscalable labelEscalable4;
    private Labels.LabelEscalable labelEscalable5;
    private Labels.LabelEscalable labelEscalable6;
    private Labels.LabelEscalable labelEscalable7;
    private Labels.TexBox texBox1;
<<<<<<< HEAD
    private Labels.TexBoxPassword texBoxPassword1;
=======
>>>>>>> 361dfb21028027730bd35f4a3cde26889096c033
    // End of variables declaration//GEN-END:variables
}
