/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_CAJERO;

/**
 *
 * @author Computacion
 */
public class Cajero extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Cajero() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        animacionLetras1 = new Componentes.AnimacionLetras();
        boton1 = new Componentes.Boton();
        boton2 = new Componentes.Boton();
        boton3 = new Componentes.Boton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        scroll_Categorias2 = new Componentes.Scroll_Categorias();
        botonLetras1 = new Componentes.BotonLetras();
        botonLetras2 = new Componentes.BotonLetras();
        botonLetras3 = new Componentes.BotonLetras();
        botonLetras4 = new Componentes.BotonLetras();
        botonLetras5 = new Componentes.BotonLetras();
        botonLetras6 = new Componentes.BotonLetras();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(252, 252, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 80));
        jPanel1.add(scroll_Categorias2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 1420, 170));

        botonLetras1.setText("Por tiempo limitado");
        botonLetras1.setToolTipText("");
        botonLetras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLetras1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLetras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 150, 40));

        botonLetras2.setText("Sándwiches");
        botonLetras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLetras2ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLetras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 150, 40));

        botonLetras3.setText("Todos");
        botonLetras3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLetras3ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLetras3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 150, 40));

        botonLetras4.setText("McMuffin");
        botonLetras4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLetras4ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLetras4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 150, 40));

        botonLetras5.setText("Hot Cakes");
        botonLetras5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLetras5ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLetras5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 150, 40));

        botonLetras6.setText("Bebidas");
        botonLetras6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLetras6ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLetras6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 150, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Elige lo que mas te gusta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 240, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 96)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Menu");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 300, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLetras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLetras1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLetras1ActionPerformed

    private void botonLetras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLetras2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLetras2ActionPerformed

    private void botonLetras3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLetras3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLetras3ActionPerformed

    private void botonLetras4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLetras4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLetras4ActionPerformed

    private void botonLetras5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLetras5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLetras5ActionPerformed

    private void botonLetras6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLetras6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLetras6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.AnimacionLetras animacionLetras1;
    private Componentes.Boton boton1;
    private Componentes.Boton boton2;
    private Componentes.Boton boton3;
    private Componentes.BotonLetras botonLetras1;
    private Componentes.BotonLetras botonLetras2;
    private Componentes.BotonLetras botonLetras3;
    private Componentes.BotonLetras botonLetras4;
    private Componentes.BotonLetras botonLetras5;
    private Componentes.BotonLetras botonLetras6;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private Componentes.Scroll_Categorias scroll_Categorias2;
    // End of variables declaration//GEN-END:variables
}
